-- Seed: initial component data
-- Generated by scripts/gen-seed.mjs

INSERT INTO components (id, name, category_slug, description, yaml, tags, sort_order)
VALUES (
  'comp-button-primary',
  'Primary Button',
  'buttons',
  'A styled primary action button with configurable color and radius',
  '- CustomButton:
    Control: Button
    Properties:
      Text: ="Submit"
      Fill: =RGBA(59, 130, 246, 1)
      Color: =RGBA(255, 255, 255, 1)
      RadiusTopLeft: =8
      RadiusTopRight: =8
      RadiusBottomLeft: =8
      RadiusBottomRight: =8
      Width: =160
      Height: =40
',
  'primary,action,cta',
  1
);

INSERT INTO components (id, name, category_slug, description, yaml, tags, sort_order)
VALUES (
  'comp-form-contact',
  'Contact Form',
  'forms',
  'A dynamic form card with title, subtitle, input fields, and action buttons',
  '- Container_Main:
    Control: GroupContainer
    Variant: ManualLayout
    Properties:
      Fill: =RGBA(255, 255, 255, 1)
      RadiusTopLeft: =16
      RadiusTopRight: =16
      RadiusBottomLeft: =16
      RadiusBottomRight: =16
      DropShadow: =DropShadow.Light
      Width: =500
      Height: =500
    Children:
      - TitleLabel:
          Control: Label
          Properties:
            Text: ="Contact Us"
            Size: =20
            FontWeight: =FontWeight.Bold
            X: =40
            Y: =40
      - SubtitleLabel:
          Control: Label
          Properties:
            Text: ="Fill in the fields below"
            Size: =12
            Color: =RGBA(100, 116, 139, 1)
            X: =40
            Y: =80
      - Label_0:
          Control: Label
          Properties:
            Text: ="Name"
            FontWeight: =FontWeight.Semibold
            X: =40
            Y: =130
      - Input_0:
          Control: TextInput
          Properties:
            Default: =""
            HintText: ="Enter your name"
            X: =40
            Y: =160
            Width: =420
            Height: =40
            BorderThickness: =1
            BorderColor: =RGBA(226, 232, 240, 1)
      - Label_1:
          Control: Label
          Properties:
            Text: ="Email"
            FontWeight: =FontWeight.Semibold
            X: =40
            Y: =220
      - Input_1:
          Control: TextInput
          Properties:
            Default: =""
            HintText: ="Enter your email"
            X: =40
            Y: =250
            Width: =420
            Height: =40
            BorderThickness: =1
            BorderColor: =RGBA(226, 232, 240, 1)
      - Label_2:
          Control: Label
          Properties:
            Text: ="Message"
            FontWeight: =FontWeight.Semibold
            X: =40
            Y: =310
      - Input_2:
          Control: TextInput
          Properties:
            Default: =""
            HintText: ="Enter your message"
            X: =40
            Y: =340
            Width: =420
            Height: =40
            BorderThickness: =1
            BorderColor: =RGBA(226, 232, 240, 1)
      - BtnPrimary:
          Control: Button
          Properties:
            Text: ="Submit"
            X: =40
            Y: =420
            Width: =200
            Height: =40
            Fill: =RGBA(59, 130, 246, 1)
      - BtnSecondary:
          Control: Button
          Properties:
            Text: ="Cancel"
            X: =260
            Y: =420
            Width: =200
            Height: =40
            Fill: =RGBA(241, 245, 249, 1)
            Color: =RGBA(71, 85, 105, 1)
',
  'form,input,card',
  1
);

INSERT INTO components (id, name, category_slug, description, yaml, tags, sort_order)
VALUES (
  'comp-badge-status',
  'Status Badge',
  'badges',
  'A small pill badge for status labels (success or info theme)',
  '- BadgeContainer:
    Control: GroupContainer
    Variant: ManualLayout
    Properties:
      Fill: =RGBA(34, 197, 94, 0.1)
      RadiusTopLeft: =4
      RadiusTopRight: =4
      RadiusBottomLeft: =4
      RadiusBottomRight: =4
      Width: =120
      Height: =32
    Children:
      - BadgeLabel:
          Control: Label
          Properties:
            Text: ="ACTIVE"
            Color: =RGBA(21, 128, 61, 1)
            FontWeight: =FontWeight.Bold
            Size: =10
            Align: =Align.Center
            Width: =120
            Height: =32
',
  'badge,status,label,pill',
  1
);

INSERT INTO components (id, name, category_slug, description, yaml, tags, sort_order)
VALUES (
  'comp-accordion-faq',
  'FAQ Accordion',
  'accordions',
  'A vertical accordion list for FAQs or expandable sections',
  '- Accordion_Main:
    Control: GroupContainer
    Variant: ManualLayout
    Properties:
      Width: =400
      Height: =180
    Children:
      - AccItem_0:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            Y: =0
            Width: =400
            Height: =50
            Fill: =RGBA(248, 250, 252, 1)
          Children:
            - AccLabel_0:
                Control: Label
                Properties:
                  Text: ="What is Power Apps?"
                  X: =15
                  Width: =370
                  VerticalAlign: =VerticalAlign.Middle
                  Height: =50
      - AccItem_1:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            Y: =60
            Width: =400
            Height: =50
            Fill: =RGBA(248, 250, 252, 1)
          Children:
            - AccLabel_1:
                Control: Label
                Properties:
                  Text: ="How do I add a component?"
                  X: =15
                  Width: =370
                  VerticalAlign: =VerticalAlign.Middle
                  Height: =50
      - AccItem_2:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            Y: =120
            Width: =400
            Height: =50
            Fill: =RGBA(248, 250, 252, 1)
          Children:
            - AccLabel_2:
                Control: Label
                Properties:
                  Text: ="Can I customise styles?"
                  X: =15
                  Width: =370
                  VerticalAlign: =VerticalAlign.Middle
                  Height: =50
',
  'accordion,faq,expand,list',
  1
);

INSERT INTO components (id, name, category_slug, description, yaml, tags, sort_order)
VALUES (
  'comp-shell-default',
  'App Shell Header',
  'app-shells',
  'A full-width app header shell with title and brand colour',
  '- AppShell:
    Control: GroupContainer
    Variant: ManualLayout
    Properties:
      Fill: =RGBA(59, 130, 246, 1)
      Width: =1366
      Height: =80
    Children:
      - AppTitle:
          Control: Label
          Properties:
            Text: ="My Power App"
            Color: =RGBA(255, 255, 255, 1)
            X: =20
            Y: =20
            Size: =20
            FontWeight: =FontWeight.Bold
',
  'shell,header,nav,layout',
  1
);

